services:
  backend:
    image: api-information
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - path: .env
        required: true
